baseURL = "https://auch.cool"
languageCode = "en-us"
title = "/home/robert"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "https://blog.auch.cool"
weight = 1

[params]
title = "/home/robert"
description = "Text about my cool site"
favicon = "/img/favicon-32x32.png"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "/home/robert"
  disableSearch = true

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Robert."
  subtitle = "Sometimes I do stuff"
  content = "Worked with a lot of servers in a hosting company, acted as GitLab Magican & Meme Integrator, tinkering on stuff that runs the internet now. Has both a stupid and pragmatic solution for every problem and likes them to be scaleable and generalized. Lost his heart to Ruby, likes photography, mountain biking and movies."
  image = "/img/robert.jpg"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = false
    name = "CV"
    url = "https://read.cv/rm"
    download = false
    newPage = true

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/flipez"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-gitlab"
url = "https://gitlab.com/flipez"

  [params.about]
  enable = false
  title = "About Me"
  image = "img/robert.jpg"
  content = """
I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

I am currently working on a project that will be used to help people find the best way to get around the city."""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = [ "HTML", "CSS", "JavaScript", "React", "Node", "Express" ]

  [params.experience]
  enable = false

  [params.education]
  enable = false

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "RocketLang"
    image = "/img/rocketlang.png"
    content = "Started as a joke to learn the inner mechanics of a interpreted language, RocketLang quickly evolved into a long running project with more and more ambitious goals, such as being used for Advent of Code to test it's limits."
    badges = [ "Golang", "Interpreter" ]

      [params.projects.items.featured]
      name = "Playground"
      link = "https://play.rocket-lang.org"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/flipez/rocket-lang"

    [[params.projects.items]]
    title = "Sticktorio"
    content = "I like idle clickers and wanted to make one myself. I also like production simulations like Factorio, Satisfactory or shapez.io. The outcome of this game is probably a mixture of these two worlds. As I did this Jam the first time alone I focused more on the content and mechanics rather than the balancing or optics - hope you enjoy it anyways!"
    image = "/img/sticktorio.png"
    badges = [ "Idle clicker", "Game Jame", "Godot" ]

      [params.projects.items.featured]
      name = "Play online"
      link = "https://flipez.itch.io/sticktorio"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/Flipez/sticktorio"

    [[params.projects.items]]
    title = "kickr.me"
    content = "Implementation of a system to detect goals and calculate rankings on a physical foosball table"
    image = "/img/kickr.png"
    badges = [ "Go", "Foosball", "Rasberry Pi", "MQTT", "Ruby on Rails" ]

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/kickr-me"

  [params.contact]
  enable = false


[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/Flipez"
linkedin = "https://www.linkedin.com/in/mueller-r/"
instagram = "https://www.instagram.com/rueller.mobert/"

  [params.listPages]
  disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"
